In [24]:
import pandas as pd
import numpy as np

In [25]:
diagnoses_df = pd.read_csv('../Data/diagnoses_icd.csv')
diagnoses_df.head()

   subject_id   hadm_id  seq_num icd_code  icd_version
0    10000032  22595853        1     5723            9
1    10000032  22595853        2    78959            9
2    10000032  22595853        3     5715            9
3    10000032  22595853        4    07070            9
4    10000032  22595853        5      496            9

In [26]:
diagnoses_codes_df = pd.read_csv('../Data/d_icd_diagnoses.csv')
diagnoses_codes_df.head()

  icd_code  icd_version                             long_title
0     0010            9         Cholera due to vibrio cholerae
1     0011            9  Cholera due to vibrio cholerae el tor
2     0019            9                   Cholera, unspecified
3     0020            9                          Typhoid fever
4     0021            9                    Paratyphoid fever A

In [27]:
kidney_disease_indices = [2668, 6001, 6002]
kidney_disease_indices += [n for n in range(4660, 4678)]
kidney_disease_indices += [n for n in range(5956, 6000)]
kidney_disease_indices += [n for n in range(6027, 6031)]
kidney_disease_indices += [n for n in range(6086, 6089)]
kidney_disease_indices += [n for n in range(6609, 6614)]
kidney_disease_indices += [n for n in range(37868, 37879)]
kidney_disease_indices += [n for n in range(37860, 37868)]
kidney_disease_indices += [n for n in range(37849, 37860)]
kidney_disease_indices = [n - 2 for n in kidney_disease_indices]
icd_codes = [diagnoses_codes_df.iloc[n]['icd_code'] for n in kidney_disease_indices]
subject_ids = []
for code in icd_codes:
    subject_ids += list(diagnoses_df.loc[diagnoses_df['icd_code'] == code, 'subject_id'])
subject_ids = list(set(subject_ids))

In [28]:
labs_df = pd.read_csv('../Data/serum_creatinine_labs.csv')
print(labs_df.shape[0])
labs_df.head()

28580

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,26,10000032,NaN,83925500,50912,P69FQC,3/23/2180 11:51,3/23/2180 16:40,0.4,0.4,mg/dL,0.4,1.1,NaN,ROUTINE,NaN
1,104,10000032,NaN,95700408,50912,NaN,5/6/2180 22:25,5/6/2180 23:16,0.3,0.3,mg/dL,0.4,1.1,abnormal,STAT,NaN
2,150,10000032,22595853.0,86271148,50912,NaN,5/7/2180 5:05,5/7/2180 7:03,0.3,0.3,mg/dL,0.4,1.1,abnormal,ROUTINE,NaN
3,175,10000032,NaN,19543630,50912,P85UQ1,6/3/2180 12:00,6/3/2180 13:04,0.4,0.4,mg/dL,0.4,1.1,NaN,ROUTINE,NaN
4,187,10000032,NaN,58691952,50912,P69FQC,6/3/2180 12:00,6/3/2180 13:04,0.4,0.4,mg/dL,0.4,1.1,NaN,ROUTINE,NaN

In [29]:
for patient in subject_ids:
    if not labs_df.loc[labs_df['subject_id'] == patient].empty:
        rows_to_drop = labs_df.loc[labs_df['subject_id'] == patient].index
        labs_df = labs_df.drop(rows_to_drop)
print(labs_df.shape[0])

11974

In [30]:
normal_kidney_ids = list(set(labs_df['subject_id']))
for patient in normal_kidney_ids:
    if diagnoses_df.loc[diagnoses_df['subject_id'] == patient].empty:
        rows_to_drop = labs_df.loc[labs_df['subject_id'] == patient].index
        labs_df = labs_df.drop(rows_to_drop)
print(labs_df.shape[0])

10760

In [31]:
labs_df.to_csv('../Data/modified_normal_kidney_patients.csv', index = False)

In [34]:
kidney_patients_df = pd.read_csv('../Data/kidney_disease_patients_labs.csv',
                                low_memory = False)
kidney_patients_df.head()

,labevent_id,subject_id,specimen_id,itemid,charttime,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,684502,10043631,98360823,50802,4/4/2172 19:23,-3.0,mEq/L,NaN,NaN,NaN,NaN,NaN
1,686100,10043631,47882645,50802,5/24/2173 21:22,1.0,mEq/L,NaN,NaN,NaN,NaN,NaN
2,686270,10043631,39825508,50802,5/30/2173 13:22,-4.0,mEq/L,NaN,NaN,NaN,NaN,NaN
3,689348,10043631,82324807,50802,5/10/2176 13:15,2.0,mEq/L,NaN,NaN,NaN,NaN,NaN
4,689354,10043631,7383321,50802,5/11/2176 9:42,1.0,mEq/L,NaN,NaN,NaN,NaN,NaN

In [36]:
kidney_ids = set(kidney_patients_df['subject_id'])
normal_ids = set(labs_df['subject_id'])
normal_ids.intersection(kidney_ids)

{10000935,
 10007795,
 10015048,
 10032651,
 10038332,
 10049461,
 10060142,
 10061468,
 10063856}

In [39]:
diagnoses_df.loc[diagnoses_df['subject_id'] == 10015048]

       subject_id   hadm_id  seq_num icd_code  icd_version
10587    10015048  21854603        1     4260            9
10588    10015048  21854603        2    42831            9
10589    10015048  21854603        3    99601            9
10590    10015048  21854603        4     7802            9
10591    10015048  21854603        5     4019            9
10592    10015048  21854603        6    28529            9
10593    10015048  21854603        7     7140            9
10594    10015048  21854603        8     2724            9
10595    10015048  21854603        9    71590            9
10596    10015048  21854603       10    V1254            9
10597    10015048  21854603       11    E8798            9
10598    10015048  21854603       12     4280            9