# Normal Kidney Diagnoses
This notebook is analogous to *kidney_disease_diagnoses.ipynb*, but pertains to patients with healthy kidneys. In particular, the objective is to create a dictionary called `normal_kidney_patient_diagnoses`, where the keys are the `subject_id` of a patient with healthy kidneys, and the values are tuples of the form `(seq_num, icd_code, icd_version)`. As in *kidney_disease_diagnoses.ipynb*, each entry in the tuple is a list whose length is determined by the number of diagnoses that the patient received. The `long_title` of the diagnosis can be obtained by using the `icd_code` in conjunction with *d_icd_diagnoses.csv*.

In [11]:
import numpy as np
import pandas as pd
import json

In [12]:
normal_kidney_data = pd.read_csv('../Data/normal_kidney_patients.csv.gz',
                                compression = 'gzip')
normal_kidney_data.head()

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,617746,10039302,25044971.0,12440596,50868,NaN,2118-02-06 00:10:00,2118-02-06 01:28:00,16,16.0,mEq/L,8.0,20.0,NaN,STAT,NaN
1,617747,10039302,25044971.0,12440596,50882,NaN,2118-02-06 00:10:00,2118-02-06 01:28:00,26,26.0,mEq/L,22.0,32.0,NaN,STAT,NaN
2,617748,10039302,25044971.0,12440596,50893,NaN,2118-02-06 00:10:00,2118-02-06 01:28:00,9.6,9.6,mg/dL,8.4,10.2,NaN,STAT,NaN
3,617749,10039302,25044971.0,12440596,50902,NaN,2118-02-06 00:10:00,2118-02-06 01:28:00,106,106.0,mEq/L,96.0,108.0,NaN,STAT,NaN
4,617750,10039302,25044971.0,12440596,50912,NaN,2118-02-06 00:10:00,2118-02-06 01:28:00,1.0,1.0,mg/dL,0.4,1.1,NaN,STAT,NaN

In [13]:
diagnoses_data = pd.read_csv('../Data/diagnoses_icd.csv')
diagnoses_data.head()

   subject_id   hadm_id  seq_num icd_code  icd_version
0    10000032  22595853        1     5723            9
1    10000032  22595853        2    78959            9
2    10000032  22595853        3     5715            9
3    10000032  22595853        4    07070            9
4    10000032  22595853        5      496            9

In [14]:
subject_ids = list(set(normal_kidney_data['subject_id']))
normal_kidney_patient_diagnoses = {}
for patient in subject_ids:
    patient_diagnoses = diagnoses_data.loc[diagnoses_data['subject_id'] == patient]
    normal_kidney_patient_diagnoses[patient] = (list(patient_diagnoses['seq_num']),
                                               list(patient_diagnoses['icd_code']),
                                               list(patient_diagnoses['icd_version']))

In [15]:
with open('../Data/normal_kidney_patient_diagnoses.json', 'w') as file:
    json.dump(normal_kidney_patient_diagnoses, file)